[system]
compatible=pizero
bootloader=uboot
data-directory=/data/

[keyring]
path=/etc/rauc/ca.cert.pem

[encryption]
key=/etc/rauc/bundle-encryption.key

[slot.rootfs.0]
device=/dev/mmcblk0p2
type=raw
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk0p3
type=raw
bootname=B