DISTRO ?= "aero-distro"
DISTRO_NAME ?= "Stupid distro ^_^"
DISTRO_VERSION ?= "1.0"

# dev / fab
IMAGE_TYPE ??= "dev"

require files/${IMAGE_TYPE}.inc

#Over engineering
#require files/${@d.getVar("IMAGE_TYPE")}.inc

DISTRO_FEATURES = "ext2"

#This feature is added by DISTRO_FEATURES_BACKFILL
DISTRO_FEATURES:remove = "pulseaudio"

#Disable GPLv3 packages :  AGPL-3.0-only AGPL-3.0-or-later GPL-3.0-only GPL-3.0-or-later LGPL-3.0-only
INCOMPATIBLE_LICENSE:pn-core-myimage = "AGPL-3.0-only AGPL-3.0-or-later GPL-3.0-only GPL-3.0-or-later LGPL-3.0-only"

#Enable image build info
INHERIT += "image-buildinfo"

#Adding rauc feature
DISTRO_FEATURES += "rauc"

#Adding wifi
DISTRO_FEATURES += "rauc"