# We define the layer here

LAYERVERSION_mycustom = "1.0"

BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# depends on openmbedded-core and meta-raspberrypi
LAYERDEPENDS_mycustom = ""
LAYERSERIES_COMPAT_mycustom = "*/"

############################# RAUC integration ###########################
RAUC_BUNDLE_ENCRYPT = "1"
RAUC_KEY_FILE ?= "${LAYERDIR}/recipes-core/rauc/files/development-1.key.pem"
RAUC_CERT_FILE ?= "${LAYERDIR}/recipes-core/rauc/files/development-1.cert.pem"
RAUC_KEYRING_FILE ?= "${LAYERDIR}/recipes-core/rauc/files/ca.cert.pem"
RAUC_ENCRYPTION_KEY ?= "${LAYERDIR}/recipes-core/rauc/files/bundle-encryption.key"
RAUC_ENCRYPTION_CERT ?= "${LAYERDIR}/recipes-core/rauc/files/bundle-encryption.cert"
######################## Initramfs Integration ###########################
INITRAMFS_IMAGE = "base-initramfs"
INITRAMFS_IMAGE_BUNDLE = "1"

# Removing hardcoded root=/dev/mmcblk0p2 rootfstype=ext4 which leads skip initramfs and directly mount rootfs
CMDLINE_ROOTFS = ""

IMAGE_BOOT_FILES:append = " Image-initramfs-${MACHINE}.bin;Image "
